### ISSUE TITLE
Cannot find module "isomorphic-fetch"

### ISSUE THREAD

**Issue by specialCoder** [bailicangdu/react-pxq#2]
在window7系统谷歌浏览器下
npm run dev
会报出一个错误：
Uncaught Error: Cannot find module "isomorphic-fetch"
    at webpackMissingModule (http://127.0.0.1:8088/pxq/dist/app.js:36468:89)
    at Object.<anonymous> (http://127.0.0.1:8088/pxq/dist/app.js:36468:182)
    at __webpack_require__ (http://127.0.0.1:8088/pxq/dist/app.js:48:30)
    at Object.<anonymous> (http://127.0.0.1:8088/pxq/dist/app.js:36375:15)
    at __webpack_require__ (http://127.0.0.1:8088/pxq/dist/app.js:48:30)
    at Object.<anonymous> (http://127.0.0.1:8088/pxq/dist/app.js:36186:18)
    at __webpack_require__ (http://127.0.0.1:8088/pxq/dist/app.js:48:30)
    at Object.<anonymous> (http://127.0.0.1:8088/pxq/dist/app.js:29562:15)
    at __webpack_require__ (http://127.0.0.1:8088/pxq/dist/app.js:48:30)
    at Object.<anonymous> (http://127.0.0.1:8088/pxq/dist/app.js:23818:15)

**Comment by bailicangdu** [comment]
Cannot find module "isomorphic-fetch" 缺少这个依赖，安装一下就行
npm install "isomorphic-fetch"

**Comment by cajan** [comment]
用淘宝镜像去安装：
先:npm install cnpm -g，
再执行:cnpm install isomorphic-fetch
包括node-sass这个也要用cnpm去安装，都是因为网络问题导致的
