### ISSUE TITLE
npm install error 

### ISSUE THREAD

**Issue by fengjingxuan8** [bailicangdu/react-pxq#49]
gyp ERR! configure error
gyp ERR! stack Error: connect ETIMEDOUT 104.20.23.46:443
gyp ERR! stack     at Object.exports._errnoException (util.js:1018:11)
gyp ERR! stack     at exports._exceptionWithHostPort (util.js:1041:20)
gyp ERR! stack     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "D:\\node\\anzhuang\\node.exe" "D:\\node\\react-pxq-master\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd D:\node\react-pxq-master\node_modules\node-sass
gyp ERR! node -v v6.10.3
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
Build failed with error code: 1
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "D:\\node\\anzhuang\\node.exe" "D:\\node\\anzhuang\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v6.10.3
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

**Comment by lurenhtml5** [comment]
我也是，这个问你你解决了吗

**Comment by onlyliii** [comment]
把package.json里面的"node-sass": "^3.13.3" 修改为"node-sass": "^4.7.2"之后使用cnpm install安装就行，亲测成功

**Comment by lovegnep** [comment]
楼上的，package.json中没有你说的这个node-sass呀
