### ISSUE TITLE
win10下安装cnpm install node-sass，总是失败，楼主有什么好的解决办法吗？百度谷歌了一堆都不起作用

### ISSUE THREAD

**Issue by Zebzhong** [bailicangdu/react-pxq#58]
node-sass build Binary found at D:\WorkCode\win32-x64-51_binding.node

> node-sass@4.5.3 postinstall F:\sxt\Stage4\react\react-pxq-master\pxq\node_modules\node-sass
> node scripts/build.js

Binary found at D:\WorkCode\win32-x64-51_binding.node
Testing binary
Binary has a problem: Error: The module '\\?\D:\WorkCode\win32-x64-51_binding.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 51. This version of Node.js requires
NODE_MODULE_VERSION 57. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at Object.Module._extensions..node (module.js:598:18)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at module.exports (F:\sxt\Stage4\react\react-pxq-master\pxq\node_modules\node-sass\lib\binding.js:19:10)
    at Object.<anonymous> (F:\sxt\Stage4\react\react-pxq-master\pxq\node_modules\node-sass\lib\index.js:14:35)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
Building the binary locally
Building: F:\node.exe F:\sxt\Stage4\react\react-pxq-master\pxq\node_modules\node-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext=
--libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [ 'F:\\node.exe',
gyp verb cli   'F:\\sxt\\Stage4\\react\\react-pxq-master\\pxq\\node_modules\\node-gyp\\bin\\node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library=' ]
gyp info using node-gyp@3.6.2
gyp info using node@8.2.1 | win32 | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb download using dist-url https://npm.taobao.org/dist
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` failed Error: not found: python2
gyp verb `which` failed     at getNotFoundError (F:\sxt\Stage4\react\react-pxq-master\pxq\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (F:\sxt\Stage4\react\react-pxq-master\pxq\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (F:\sxt\Stage4\react\react-pxq-master\pxq\node_modules\which\which.js:80:29)
gyp verb `which` failed     at F:\sxt\Stage4\react\react-pxq-master\pxq\node_modules\which\which.js:89:16
gyp verb `which` failed     at F:\sxt\Stage4\react\react-pxq-master\pxq\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at F:\sxt\Stage4\react\react-pxq-master\pxq\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:152:21)
gyp verb `which` failed  python2 { Error: not found: python2
gyp verb `which` failed     at getNotFoundError (F:\sxt\Stage4\react\react-pxq-master\pxq\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (F:\sxt\Stage4\react\react-pxq-master\pxq\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (F:\sxt\Stage4\react\react-pxq-master\pxq\node_modules\which\which.js:80:29)
gyp verb `which` failed     at F:\sxt\Stage4\react\react-pxq-master\pxq\node_modules\which\which.js:89:16
gyp verb `which` failed     at F:\sxt\Stage4\react\react-pxq-master\pxq\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at F:\sxt\Stage4\react\react-pxq-master\pxq\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:152:21)
gyp verb `which` failed   stack: 'Error: not found: python2\n    at getNotFoundError (F:\\sxt\\Stage4\\react\\react-pxq-master\\pxq\\n
ode_modules\\which\\which.js:13:12)\n    at F (F:\\sxt\\Stage4\\react\\react-pxq-master\\pxq\\node_modules\\which\\which.js:68:19)\n
  at E (F:\\sxt\\Stage4\\react\\react-pxq-master\\pxq\\node_modules\\which\\which.js:80:29)\n    at F:\\sxt\\Stage4\\react\\react-pxq-
master\\pxq\\node_modules\\which\\which.js:89:16\n    at F:\\sxt\\Stage4\\react\\react-pxq-master\\pxq\\node_modules\\isexe\\index.js:
42:5\n    at F:\\sxt\\Stage4\\react\\react-pxq-master\\pxq\\node_modules\\isexe\\windows.js:36:5\n    at FSReqWrap.oncomplete (fs.js:1
52:21)',
gyp verb `which` failed   code: 'ENOENT' }
gyp verb check python checking for Python executable "python" in the PATH
gyp verb `which` succeeded python C:\Python27\python.EXE
gyp verb check python version `C:\Python27\python.EXE -c "import platform; print(platform.python_version());"` returned: "2.7.13\r\n"
gyp verb get node dir no --target version specified, falling back to host node version: 8.2.1
gyp verb command install [ '8.2.1' ]
gyp verb download using dist-url https://npm.taobao.org/dist
gyp verb install input version string "8.2.1"
gyp verb install installing version: 8.2.1
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version is already installed, need to check "installVersion"
gyp verb got "installVersion" 9
gyp verb needs "installVersion" 9
gyp verb install version is good
gyp verb get node dir target node version installed: 8.2.1
gyp verb build dir attempting to create "build" dir: F:\sxt\Stage4\react\react-pxq-master\pxq\node_modules\node-sass\build
gyp verb build dir "build" dir needed to be created? F:\sxt\Stage4\react\react-pxq-master\pxq\node_modules\node-sass\build
gyp verb Not using VS2017: Could not use PowerShell to find VS2017
gyp verb build/config.gypi creating config file
gyp verb build/config.gypi writing out config file: F:\sxt\Stage4\react\react-pxq-master\pxq\node_modules\node-sass\build\config.gypi
gyp verb config.gypi checking for gypi file: F:\sxt\Stage4\react\react-pxq-master\pxq\node_modules\node-sass\config.gypi
gyp verb common.gypi checking for gypi file: F:\sxt\Stage4\react\react-pxq-master\pxq\node_modules\node-sass\common.gypi
gyp verb gyp gyp format was not specified; forcing "msvs"
gyp info spawn C:\Python27\python.EXE
gyp info spawn args [ 'F:\\sxt\\Stage4\\react\\react-pxq-master\\pxq\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-G',
gyp info spawn args   'msvs_version=auto',
gyp info spawn args   '-I',
gyp info spawn args   'F:\\sxt\\Stage4\\react\\react-pxq-master\\pxq\\node_modules\\node-sass\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'F:\\sxt\\Stage4\\react\\react-pxq-master\\pxq\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\zhongbin\\.node-gyp\\8.2.1\\include\\node\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\zhongbin\\.node-gyp\\8.2.1',
gyp info spawn args   '-Dnode_gyp_dir=F:\\sxt\\Stage4\\react\\react-pxq-master\\pxq\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=C:\\Users\\zhongbin\\.node-gyp\\8.2.1\\<(target_arch)\\node.lib',
gyp info spawn args   '-Dmodule_root_dir=F:\\sxt\\Stage4\\react\\react-pxq-master\\pxq\\node_modules\\node-sass',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'F:\\sxt\\Stage4\\react\\react-pxq-master\\pxq\\node_modules\\node-sass\\build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp verb command build []
gyp verb download using dist-url https://npm.taobao.org/dist
gyp verb build type Release
gyp verb architecture x64
gyp verb node dev dir C:\Users\zhongbin\.node-gyp\8.2.1
gyp verb found first Solution file build/binding.sln
gyp verb could not find "msbuild.exe" in PATH - finding location in registry
gyp info spawn C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe
gyp info spawn args [ 'build/binding.sln',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=x64' ]
在此解决方案中一次生成一个项目。若要启用并行生成，请添加“/m”开关。
生成启动时间为 2017/9/5 23:01:13。
节点 1 上的项目“F:\sxt\Stage4\react\react-pxq-master\pxq\node_modules\node-sass\build\binding.sln”(默认目标)。
ValidateSolutionConfiguration:
  正在生成解决方案配置“Release|x64”。
MSBUILD : error MSB3428: 未能加载 Visual C++ 组件“VCBuild.exe”。要解决此问题，1) 安装 .NET Framework 2.0 SDK；2) 安装 Microsoft Visu
al Studio 2005；或 3)
如果将该组件安装到了其他位置，请将其位置添加到系统路径中。 [F:\sxt\Stage4\react\react-pxq-master\pxq\node_modules\node-sass\build\bind
ing.sln]
已完成生成项目“F:\sxt\Stage4\react\react-pxq-master\pxq\node_modules\node-sass\build\binding.sln”(默认目标)的操作 - 失败。

生成失败。

“F:\sxt\Stage4\react\react-pxq-master\pxq\node_modules\node-sass\build\binding.sln”(默认目标) (1) ->
(_src_\libsass 目标) ->
  MSBUILD : error MSB3428: 未能加载 Visual C++ 组件“VCBuild.exe”。要解决此问题，1) 安装 .NET Framework 2.0 SDK；2) 安装 Microsoft Vi
sual Studio 2005；或 3
) 如果将该组件安装到了其他位置，请将其位置添加到系统路径中。 [F:\sxt\Stage4\react\react-pxq-master\pxq\node_modules\node-sass\build\bi
nding.sln]

    0 个警告
    1 个错误

已用时间 00:00:00.10
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (F:\sxt\Stage4\react\react-pxq-master\pxq\node_modules\node-gyp\lib\build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:125:13)
gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Windows_NT 10.0.15063
gyp ERR! command "F:\\node.exe" "F:\\sxt\\Stage4\\react\\react-pxq-master\\pxq\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "-
-verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd F:\sxt\Stage4\react\react-pxq-master\pxq\node_modules\node-sass
gyp ERR! node -v v8.2.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
Build failed with error code: 1
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@4.5.3 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@4.5.3 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\zhongbin\AppData\Roaming\npm-cache\_logs\2017-09-05T15_01_19_896Z-debug.log

**Comment by by-oneself** [comment]
使用npm安装

**Comment by Zebzhong** [comment]
还是一样

**Comment by wangerniu** [comment]
node-sass好像出问题了。我这儿也安装不上

**Comment by wangerniu** [comment]
从其他项目里的node_modules中，挪一个node-sass过来就能解决这个问题。

**Comment by fuhaichao122** [comment]
我把node-sass版本号换了"node-sass": "^4.5.3",结果没有问题了。我也是win10 ，可以试试。

**Comment by starmarker** [comment]
我这也失败……从新找个项目看看了只能！

**Comment by wangerniu** [comment]
尽量不要使用cnpm安装以来，这家伙最近有点不靠谱，老是丢包，开发的时候莫名奇妙的会报`什么什么module is undifined `。
推荐使用翻墙+npm

**Comment by nidilong** [comment]
这样试试：
npm config set registry https://registry.npm.taobao.org --global
npm config set disturl https://npm.taobao.org/dist --global
npm config set sass-binary-site http://npm.taobao.org/mirrors/node-sass

然后 npm install node-sass

**Comment by whatlife** [comment]
@Zebzhong  推荐使用cnpm install安装. 在package.json里将node-sass版本更换成3.4.2

**Comment by tinypoint** [comment]
安装python2.7
全局安装一下node-gpy，npm i -g node-gpy
再安装node-sass

**Comment by onlyliii** [comment]
把package.json里面的"node-sass": "^3.13.3" 修改为"node-sass": "^4.7.2"之后使用cnpm install安装就行
