### ISSUE TITLE
cnpm i 一直失败找不到问题

### ISSUE THREAD

**Issue by nearxu** [bailicangdu/react-pxq#73]
× Install fail! UnSupportedPlatformError: Package require os(darwin) not compatible with your p
latform(win32)
UnSupportedPlatformError: Package require os(darwin) not compatible with your platform(win32)
    at _install (C:\Users\24488\AppData\Roaming\npm\node_modules\cnpm\node_modules\npminstall\lib\install.js:197:19)
    at _install.next (<anonymous>)
    at onFulfilled (C:\Users\24488\AppData\Roaming\npm\node_modules\cnpm\node_modules\co\index.js:65:19)
    at <anonymous>

**Comment by bh5858** [comment]
嗯，我也报错
